# Generated by Django 2.2.11 on 2020-03-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0002_auto_20200307_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
    ]
