# Generated by Django 2.2.11 on 2020-03-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0003_remove_membership_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coworking',
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Coworking',
        ),
    ]
