# Generated by Django 2.2.11 on 2020-03-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0004_auto_20200315_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebUrl', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.Contact')),
            ],
        ),
    ]
