# Generated by Django 2.2.11 on 2020-03-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0005_contact_coworking'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='linkedin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedinUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='socialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.facebook')),
                ('instagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.instagram')),
                ('linkedin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.linkedin')),
                ('twitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.twitter')),
            ],
        ),
    ]
