# Generated by Django 2.2.11 on 2020-03-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0009_auto_20200316_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='socialMedia',
        ),
    ]
