# Generated by Django 2.2.11 on 2020-03-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0013_auto_20200316_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebUrl', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='linkedin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedinUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='socialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.facebook')),
                ('instagram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.instagram')),
                ('linkedin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.linkedin')),
                ('twitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.twitter')),
            ],
        ),
        migrations.CreateModel(
            name='Coworking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiRest.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='socialMedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.socialMedia'),
        ),
    ]
