# Generated by Django 2.2.11 on 2020-03-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0016_contact_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasWifi', models.BooleanField(default=False)),
                ('hasClimatization', models.BooleanField(default=False)),
                ('is24h', models.BooleanField(default=False)),
                ('hasCoffe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='communityServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasEvents', models.BooleanField(default=False)),
                ('hasWorkshops', models.BooleanField(default=False)),
                ('hasAccelerator', models.BooleanField(default=False)),
                ('hasIncubator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='conferenceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferenceRoomName', models.CharField(max_length=128)),
                ('totalPlaces', models.IntegerField(null=True)),
                ('pricePerDay', models.IntegerField(null=True)),
                ('pricePerWeek', models.IntegerField(null=True)),
                ('pricePerMonth', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=128)),
                ('openingHours', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('openingDate', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskTypeName', models.CharField(max_length=128)),
                ('totalPlaces', models.IntegerField(null=True)),
                ('pricePerDay', models.IntegerField(null=True)),
                ('pricePerWeek', models.IntegerField(null=True)),
                ('pricePerMonth', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=128)),
                ('openingHours', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceCode', models.IntegerField()),
                ('munipalityCode', models.IntegerField()),
                ('streetCode', models.IntegerField()),
                ('postalCode', models.CharField(max_length=128)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='meetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('capacity', models.IntegerField(null=True)),
                ('pricePerDay', models.IntegerField(null=True)),
                ('pricePerWeek', models.IntegerField(null=True)),
                ('pricePerMonth', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=128)),
                ('openingHours', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='relaxServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasTerrace', models.BooleanField(default=False)),
                ('hasChillOutArea', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicServices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.basicServices')),
                ('communityServices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.communityServices')),
                ('relaxServices', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.relaxServices')),
            ],
        ),
        migrations.CreateModel(
            name='meetingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.ManyToManyField(to='ApiRest.meetingRoom')),
            ],
        ),
        migrations.CreateModel(
            name='desks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.ManyToManyField(to='ApiRest.desk')),
            ],
        ),
        migrations.CreateModel(
            name='conferenceRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.ManyToManyField(to='ApiRest.conferenceRoom')),
            ],
        ),
        migrations.AddField(
            model_name='coworking',
            name='conferenceRooms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.conferenceRooms'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='description',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.description'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='desks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.desks'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.location'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='meetingRooms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.meetingRooms'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='services',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.services'),
        ),
    ]
