# Generated by Django 2.2.11 on 2020-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0017_auto_20200317_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedin',
            name='linkedinUrl',
            field=models.CharField(max_length=130),
        ),
    ]
