# Generated by Django 2.2.11 on 2020-03-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0018_auto_20200317_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='conferenceRooms',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.conferenceRooms'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='description',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.description'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='desks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.desks'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.location'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='meetingRooms',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.meetingRooms'),
        ),
        migrations.AlterField(
            model_name='coworking',
            name='services',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiRest.services'),
        ),
    ]
