# Generated by Django 2.2.11 on 2020-03-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0019_auto_20200317_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
